-- ---------------------------------------------------------------------------
-- Member-graded activities (REMOVED).
--
-- These activities were originally seeded here but have been removed in
-- migration 20260927000000_remove_seeded_activities.sql.
-- ---------------------------------------------------------------------------